
import UIKit

class ViewController: UIViewController {
    
    
    var count = 0


    var game = [Question]()
    var currentQuestion = Question(text: "default")

    
    
    @IBOutlet weak var myLabel: UILabel!
    
    @IBOutlet weak var buttonYes: UIButton!
    
    @IBOutlet weak var buttonNO: UIButton!
    

    @IBOutlet weak var buttonIDK: UIButton!
    
    var properties = ["Female", "Math Teacher","English Teacher", "Science Teacher", "History Teacher", "Language Teacher","Art Teacher","Second Floor", "Third Floor", "First Floor", "H-Vision", "Marines", "Beard", "Micheal", "Black Wavy Hair", "Translationary", "AP Psych", "Blond Straight Hair", "U.S History", "Ceramics", "Last Name A TV Show", "AP Bio", "Curly Hair", "Marathons", "Anatomy and Physiology", "Classroom Near The Library", "AP Gov", "White Hair", "Librarian", "Health Teacher", "Business Teacher", "Security", "Best of Baking", "11th Grade English", "Ipad", "Karaoke", "Forensic Chemistry", "Suits", "Sewing Teacher", "Ginger", "No Hair", "Short" ]


    var teachers = [
        ["Name": "Mr. Walter",
         "Female": false,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
        
        ["Name": "Ms. Laskaris",
         "Female": true,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": true ],
        
        ["Name": "Mr. Althouse",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": true,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": true,
         "Marines": false,
         "Beard": true,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        ["Name": "Mr. Bilotti",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": true,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
    
        
        ["Name": "Mr. Bruno",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": true,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": true,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Ms. Cleary",
         "Female": true,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": true,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Mrs. Colby",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": true,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": true,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Mr. Cunicelli",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": true,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
        
        
        ["Name": "Mr. Decina",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": true,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
       
       
        ["Name": "Mrs. Federico",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": true,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": true,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": true ],
        
    
        ["Name": "Mr. Feely",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": true,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": true,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        ["Name": "Mr. Walter",
         "Female": false,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
        
        
        ["Name": "Mr. Foster",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true, // check
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": true,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
        
        
        ["Name": "Mr. Walter",
         "Female": false,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
        
        
        ["Name": "Mrs. Goetz",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": true,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        
        ["Name": "Mrs. Hartman",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": true,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": true,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Ms. Heuisler",
         "Female": true,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": true,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": true,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        // change to best of baking ---s
        
        ["Name": "Mr. Howe",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true, // check room number
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": true,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": true,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
        
        
        ["Name": "Mr. Hulea",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": true,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": true,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": true,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Mrs. Jackson",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": true,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": true,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Mr. Latrano",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": true,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false && true,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": true,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Mr. MacConnell",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": true,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],

    
        ["Name": "Mrs. Malligan",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": true,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
        ["Name": "Mrs. Marshall",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": true,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": true,
         "U.S History": false,
         "Ceramics": true,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
    
        
        
        ["Name": "Mrs. McCarty",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": true,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
   
        ["Name": "Mr. Mcmahon",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": true,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": true,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": true,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": true,
         "Short": false ],
    
        ["Name": "Mrs. McMahon",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": true,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
        
        ["Name": "Ms. Montgomery",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": true,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": true,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
        ["Name": "Ms. Mortland",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": true,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
        
        ["Name": "Dr. Peterson",
         "Female": false,
         "Math Teacher": true,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": true,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
   
        ["Name": "Dr. Pollard",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": true,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": true,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
        ["Name": "Mrs. Pompetti",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": true,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": true,
         "Second Floor": false,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": true,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
    
        ["Name": "Mr. Reiff",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": true,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": true,
         "Sewing Teacher": false,
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        ["Name": "Mrs. Shanne",
         "Female": true,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": false,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": false,
         "First Floor": true,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": false,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": true, //check
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": true, //check
         "Ginger": false,
         "No Hair": false,
         "Short": false ],
        
        
        ["Name": "Mr. Taraborrelli",
         "Female": false,
         "Math Teacher": false,
         "Science Teacher": false,
         "English Teacher": false,
         "History Teacher": true,
         "Art Teacher": false,
         "Language Teacher": false,
         "Third Floor": false,
         "Second Floor": true,
         "First Floor": false,
         "H-Vision": false,
         "Marines": false,
         "Beard": false,
         "Micheal": false,
         "Black Wavy Hair": false,
         "Marathons": false,
         "Anatomy and Physiology": false,
         "Classroom near Library": false,
         "Translationary": false,
         "AP Psych": false,
         "Blonde Straight Hair": false,
         "U.S History": false,
         "Ceramics": false,
         "Last Name a TV Show": false,
         "AP Bio": false,
         "Curly Hair": false,
         "AP Gov": true,
         "White Hair": false,
         "Librarian": false,
         "Health Teacher": false,
         "Business Teacher": false,
         "Security": false,
         "Best of Baking": false,
         "11th Grade English": false,
         "Ipad": false,
         "Karaoke": false,
         "Forensic Chemistry": false,
         "Suits": false,
         "Sewing Teacher": false,
         "Ginger": true,
         "No Hair": false,
         "Short": false ],
    ]
    
     
    override func viewDidLoad() {
        questionsForGAME()
        loadQuestion(question: count)
}
    
    

        
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "one" {
            let destination = segue.destination as! UserinputView
            destination.games = teachers
            
        }
      
    }
    
    func questionsForGAME(){
        game.append(Question(text: "Is your teacher a female?"));
        game.append(Question(text: "Are they a Math teacher?"));
        game.append(Question(text: "Are they an English teacher?"));
        game.append(Question(text: "Are they a Science teacher?"));
        game.append(Question(text: "Are they a History teacher?"));
        game.append(Question(text: "Are they a Language teacher?"));
        game.append(Question(text: "Are they an Art teacher?"));
        game.append(Question(text: "Are they on the second floor?"));
        game.append(Question(text: "Are they on the third floor?"));
        game.append(Question(text: "Are they on the first floor?"));
        game.append(Question(text: "Are they in charge of H-Vision?"));
        game.append(Question(text: "Have they been in the Marines?"));
        game.append(Question(text: "Do they have a beard?"));
        game.append(Question(text: "Is their first name the feminine version of Micheal?"));
        game.append(Question(text: "Do they have black wavy hair?"));
        game.append(Question(text: "Do they play translationary in their classroom?"));
        game.append(Question(text: "Have they ever taught AP Psych?"));
        game.append(Question(text: "Do they have blonde straight hair?"));
        game.append(Question(text: "Have they taught U.S History?"));
        game.append(Question(text: "Have they taught a Ceramics class?"));
        game.append(Question(text: "Is their last name a Tv Show?"));
        game.append(Question(text: "Have they taught AP Bio before?"));
        game.append(Question(text: "Do they have really curly hair?"));
        game.append(Question(text: "Do they enjoy marathons?"));
        game.append(Question(text: "Have they taught an Anatomy and Physiology?"));
        game.append(Question(text: "Do they have a classroom near the library?"));
        game.append(Question(text: "Have they taught an AP Gov class before?"));
        game.append(Question(text: "Do they have white hair?"));
        game.append(Question(text: "Are they a Librarian?"));
        game.append(Question(text: "Are they a Health teacher?"));
        game.append(Question(text: "Are they a Business teacher?"));
        game.append(Question(text: "Are they apart of Security?"));
        game.append(Question(text: "Do they teach Best of Baking?"));
        game.append(Question(text: "Have they taught an 11th grade English class?"));
        game.append(Question(text: "Do they carry around an Ipad?"));
        game.append(Question(text: "Do they have daily karaoke sessions?"));
        game.append(Question(text: "Do they teach Forensic Chemistry?"));
        game.append(Question(text: "Do they tend to wear a lot of suits?"));
        game.append(Question(text: "Are they a sewing teacher?"));
        game.append(Question(text: "Are they a ginger?"));
        game.append(Question(text: "Do they lack hair?"));
        game.append(Question(text: "Are they short?"));
}
    
    
    
    func loadQuestion(question: Int) {
        if teachers.count > 1 {
            myLabel.text = game[count].text

        }
        
        }
    
    
    
    
    
    
    
    
    
     
    
    
    func check(answer: Bool, property: String)
    {
   
        print("Before filter \(teachers.count)")
        for i in stride(from: teachers.count-1, through: 0, by: -1) {
            let teacherAnswer = teachers[i][property] as! Bool
            
            if answer != teacherAnswer
            {
                teachers.remove(at: i)
            }
            
        }
        print("After filter \(teachers.count)")
        if teachers.count == 1
        {
            print("It's your teacher \(teachers[0]["Name"] as! String)")
            myLabel.text = "Your teacher is \(teachers[0]["Name"] as! String)"
            
            teachers.remove(at: 0)
        }
        
        
//
//        if count > properties.count-1
//        {
//            count = 0
//
//        }
//
    }
    
    @IBAction func yesButton(_ sender: Any) {
        check(answer: true, property: properties[count])
        count += 1

        loadQuestion(question: count)
        
        if teachers.count < 1
        {
            YesAlerts()
        }
        
        
    }

    
    @IBAction func noButton(_ sender: Any) {
        check(answer: false, property: properties[count])
        count += 1
        loadQuestion(question: count)
        
      if teachers.count < 1
      {
//            performSegue(withIdentifier: "one", sender: self)
//            NoAlerts()
        presentAlertController()
      }

        }
        
        func YesAlerts()
        {
           
          
        }
        
        func NoAlerts()
        {
            let alertController = UIAlertController(title: "Add new tag", message: nil, preferredStyle: .alert)
                 let confirmAction = UIAlertAction(title: "Add", style: .default) { (_) in
                     if let txtField = alertController.textFields?.first, let text = txtField.text {
                         // operations
                         print("Text==>" + text)
                     }
                 }
                 let cancelAction = UIAlertAction(title: "Cancel", style: .cancel) { (_) in }
                 alertController.addTextField { (textField) in
                     textField.placeholder = "Tag"
                 }
                 alertController.addAction(confirmAction)
                 alertController.addAction(cancelAction)
                 self.present(alertController, animated: true, completion: nil)
        }
    
    
    func presentAlertController() {
        let alertController = UIAlertController(title: "Help Sabrina.AI get better", message: nil, preferredStyle: .alert)
        self.present(alertController, animated: true)
        
        alertController.addTextField { (textField) in
            textField.placeholder = "Name Teacher"
        }
        alertController.addTextField { (textField) in
            textField.placeholder = "Question that true"
//            textField.isSecureTextEntry = true
        }
        
        let continueAction = UIAlertAction(title: "Continue", style: .default) { [weak alertController] _ in
                guard let textFields = alertController?.textFields else { return }

            let addTeacher = textFields[0].text ?? ""
            let addQuestion = textFields[1].text ?? ""
            print("Teacher: \(addTeacher)")
            print("Question: \(addQuestion)")
            
            if addQuestion.count > 2{
                let lastW = addQuestion.components(separatedBy: " ")
                
                let addProperty = lastW[lastW.count-2] + " " + lastW[lastW.count-1]
                print(addProperty)
               // print(lastW[lastW.count-2])
                
            }
          
        }
        alertController.addAction(continueAction)
    }

//    override func viewDidAppear(_ animated: Bool) {
//        super.viewDidAppear(animated)
//        self.presentAlertController()
//    }

    
    }
    
    
    
    
    
    
    
    
    
    
    


struct Question{
    let text: String
}




